### ISSUE TITLE
Support for long and long long missing?

### ISSUE THREAD

**Issue by firesurfer** [aminroosta/sqlite_modern_cpp#104]
Hi,
according to the documentation in your examples this library should support long and long long as types:

```
// inserts a new user record.
		// binds the fields to '?' .
		// note that only types allowed for bindings are :
		//      int ,long, long long, float, double
		//      string , u16string
		// sqlite3 only supports utf8 and utf16 strings, you should use std::string for utf8 and std::u16string for utf16.
		// note that u"my text" is a utf16 string literal of type char16_t * .
		db << "insert into user (age,name,weight) values (?,?,?);"
			<< 20
			<< u"bob"
			<< 83.25;
```

But when I'm trying use it with a long value I get this error:

```
 error: undefined reference to 'sqlite::database_binder& sqlite::operator<< <long>(sqlite::database_binder&, long const&)'

```

Casting the value to an int before using it in the statement makes it work. 
When I took a look at the `sqlite_modern_cpp.h` file I can't find a fitting function for long values.

So is the documentation wrong or am I just to stupid to use it with a long?

**Comment by aminroosta** [comment]
@firesurfer We are supporting `int` and `sqlite3_int64` which is defined by sqlite.

On my machine `long long` works but `long` gives an error.
Thanks for opening an issue, i will look into it.
