### ISSUE TITLE
Strange error related to a trigger.

### ISSUE THREAD

**Issue by mtissington** [aminroosta/sqlite_modern_cpp#108]
I'm very confused right now. I'm getting an error 1 (database logic) when I do an update on a table backed by a trigger - I'm posting this issue here because it only occurs when I go through sqlite_modern. Any other tool I use and the sql executes correctly. Stepping into the code the error is generated on prepare.

The statement I'm trying to execute is

`*awdb_ << u"UPDATE actions SET used = 1, last_used = DATETIME('now') WHERE uuid = ?" 
<< action_uuid;`

The trigger is 

`CREATE TRIGGER actions_statistics AFTER UPDATE OF used ON actions 
BEGIN 
INSERT INTO statistics_type (date, type_uuid, count) SELECT CURRENT_DATE, new.type_uuid, 1 WHERE (SELECT Changes() = 0); 
END`

There is something in the INSERT statement in the trigger that is causing the prepare stmt to fail.
But this only happens with sqlite_modern. I'm wondering if there is anything in how you open the database that might cause this ... aside from the obvious, the database is not readonly.

**Comment by aminroosta** [comment]
@mtissington I'm not sure what's wrong.
The trigger seems fine to me, i almost understand what's going on.
What does the `WHERE (SELECT Changes() = 0)` part do?

> I'm posting this issue here because it only occurs when I go through sqlite_modern.

If you  a much simpler trigger like the following do you still get the same error?
`CREATE TRIGGER actions_statistics AFTER UPDATE OF used ON actions BEGIN INSERT INTO statistics_type (date, type_uuid, count) values(DATETIME('now'), 0, 1); END`

**Comment by mtissington** [comment]
`WHERE (SELECT Changes() = 0)` ensures the INSERT only does something if the previous SQL statement did not modify any rows.

OK - I now know what is causing it to fail, but not why it only happens under sqlite_modern.
I have a CHECK constraint on the date column to ensure that it is the correct format, 'YYYY-MM-DD'.
For some reason DATETIME('now') is a different format. When opening the database do you do anything with the locale?

**Comment by zauguin** [comment]
DATETIME by design returns the date and the time, so if you only want the
date you have to use DATE instead.

But this shouldn't depend on the binding or the locale.

**Comment by mtissington** [comment]
Yes I am aware of that - what I am puzzled by is why it failed on prepare stmt and worked inside of a third party tool. For now I have a work around.
