### ISSUE TITLE
sqlite error log?

### ISSUE THREAD

**Issue by bstarynk** [aminroosta/sqlite_modern_cpp#109]
It would be nice to be able to interface with [sqlite3_config](https://sqlite.org/c3ref/config.html) for [error logging](https://sqlite.org/errlog.html) with [SQLITE_CONFIG_LOG](https://sqlite.org/c3ref/c_config_covering_index_scan.html).

Perhaps we would want to be able to code

    sqlite::error_log([&](int errcode, const char*msg) {
      std::clog<<"SQLITE ERROR " << errcode << ":" << msg << std:endl;
    });

What do you think?

I might provide a small patch if we agree on that API.

Thanks.

[Basile Starynkevitch](http://starynkevitch.net/Basile/)  :   `basile`  at `starynkevitch` dot `net`
(France)

**Comment by aminroosta** [comment]
@bstarynk I think we should somehow use our `sqlite::exceptions` namespace.
We don't want users figuring out `error_type` from `error_code`.  

A simple solution may be:
```c++
sqlite::error_log([](sqlite_exception e) {
     cerr  << e.get_code() << ": " << e.what() << " during "
	      << e.get_sql() << endl; // Now we also have .get_sql() :-)
});
```
I am also wondering how can we efficiently overload that function on exceptions from `sqlite::exceptions` namespace. @zauguin :-)

```c++
sqlite::error_log([](sqlite::exceptions::internal e) { });
sqlite::error_log([](sqlite::exceptions::full e) { });
// ...
```

**Comment by zauguin** [comment]
I think it would be easier to specify all overloads in a sigle call, like
``` c++
sqlite::error_log(
    [](sqlite::exceptions::internal e) {
      // Do sth.
    }),
    [](sqlite::exceptions::full e) {
      // Do sth.
    }),
    ...
    );
```
Otherwise we would need some kind of runtime list for this.

This can easily be implemented on top of the basic functionality. Anyway `.get_sql()` will return an empty string, because AFAICT the current SQL statement is not available.

**Comment by aminroosta** [comment]
@zauguin Looks perfect to me 👍 

@bstarynk What do you think, does zauguin api works for you?

**Comment by bstarynk** [comment]
I am not sure to follow you. It looks you think of C++ exceptions.
I was just thinking of adding an error log function.

**Comment by aminroosta** [comment]
@bstarynk 
```c++
sqlite::error_log([&](int errcode, const char*msg) {
  std::clog<<"SQLITE ERROR " << errcode << ":" << msg << std:endl;
});
```
With this interface we need to check errorcode to determine the type of an error / exception.

For each sqlite error message we have a corresponding class in `sqlite::exceptions` namespace.
The `sqlite::exceptions::*` classes have both `errorcode` and `msg`.

In addition to sqlite exceptions we also have some exceptions for invalid use of the library like `sqlite::exceptions::more_rows`, `::no_rows`, `::reexecution` and `::mroe_statements`.

So my suggestion is to pass the exception object itself to the new `sqlite::error_log()` function.  
We also can overload on the exception type.

**Comment by aminroosta** [comment]
@bryant1410 also take a look at @zauguin  implementation #110
