### ISSUE TITLE
select last record from column? 

### ISSUE THREAD

**Issue by j4rv1s1** [aminroosta/sqlite_modern_cpp#119]
hi i have this little part of code in c++ here and i tried using the sqlite syntax in order to select, as the title says, the last record in my column but it doesn't work when i compile. 

```
database db("test.db");
 
      vector<char> ris1;
      db << "SELECT var1 from corrette order by id desc limit 1;" >> [](string ris1) {   
        cout << ris1 << '\n';
```

i tried with this command "SELECT var1 from corrette order by id desc limit 1;" but it doesn't seems to work, any tip?

**Comment by Killili** [comment]
Maybe you should direct questions about general SQL problems to http://stackoverflow.com/ or similar help sites. If it turns out to be a problem with this wrapper, we are happy to help, though.
