### ISSUE TITLE
wish: preprocessor symbols related to API (and API changes)

### ISSUE THREAD

**Issue by bstarynk** [aminroosta/sqlite_modern_cpp#121]
Just a wish: it would be nice if we had some preprocessor symbols related to API and its changes.
For example, the `database_binder::reset` method has been removed (which is actually a nice feature, i.e. the *autoreset* commit 219614b3efeccdde596dc4bfb58490), but it would be nice to have some preprocessor symbols related to it.

I'm just thinking of eg:
`#define SQLITE_MODERN_CPP_API_VERSION 5`
which would be incremented with each *incompatible* API change, or something more subtle (e.g. inspired by [gccjit symbol tags](https://gcc.gnu.org/onlinedocs/jit/topics/compatibility.html)...)

**Comment by zauguin** [comment]
@aminroosta Sorry, I pushed an implementation of this into your `master` by accident(82e3c2a2328b1c23b66c9b36e8c51035c66b5761). Should we keep it or revert it?

**Comment by aminroosta** [comment]
@zauguin Looks good to me 👍, we don't need to revert it.
