### ISSUE TITLE
Select entire row of unknown length

### ISSUE THREAD

**Issue by alexmerkel** [aminroosta/sqlite_modern_cpp#133]
Is it possible to select an entire row (using SELECT * FROM...) if the number of columns is unknown and have the result returned as a vector or array?

**Comment by aminroosta** [comment]
@alexmerkel No that's not possible. Unfortunately right now `std::vector` is only used for `blob` data.

We are however thinking about redesigning the interface in the next version.
We have a good discussion in #27
