### ISSUE TITLE
my sqlite c++ wrapper

### ISSUE THREAD

**Issue by pejman-hkh** [aminroosta/sqlite_modern_cpp#134]
https://github.com/pejman-hkh/sqlite-cpp-wrapper

**Comment by funilrys** [comment]
Please provide a description 😒

**Comment by pejman-hkh** [comment]
> Description about what ?

**Comment by aminroosta** [comment]
@pejman-hkh Your wrapper looks very good, Well Done 👍 

For SqlLite wrappers [this repository](https://github.com/SRombauts/SQLiteCpp) is the most popular and the author is kind enough to suggest alternatives repositories in the readme.
I'd suggest you add PR adding a link to yours.

**Comment by pejman-hkh** [comment]
Thanks amin,
I have writed it for mysql too.

https://github.com/pejman-hkh/mysql-cpp-wrapper

**Comment by Killili** [comment]
Looks interesting.

A few tips:

- put youre stuff in a namespace to avoid collisions:
e.g. there is a function named ```exit()``` in the global namespace someone using youre stuff might want that name ;)
- Use save conversion functions:
http://www.eternallyconfuzzled.com/arts/jsw_art_atoi.aspx
- short names are nice but using something like "var" which is a keyword in some other languages is not a good idea. Consider something like "pejman::variable_storage". Autocomplete is youre friend.
- ident youre code with either tab or spaces and try to be consistent.
- dont import stuff in the middle of youre header into the global namespace, everybody will only look in the head if something collides.

**Comment by pejman-hkh** [comment]
@Killili Thanks a lot about tips. i will update it.
