### ISSUE TITLE
extract and print values?

### ISSUE THREAD

**Issue by j4rv1s1** [aminroosta/sqlite_modern_cpp#136]
hi i tried but without no luck to select from my columns random text strings by choosing a random ID but how exactly can i print in console a random quote inside available inside my db? this thing is driving me crazy >.<

**Comment by Killili** [comment]
Hello @j4rv1s1,
i think youre problem is not with this API but more with the basics of SQL as a language.
Please ask youre question at a more specialized platform like stackoverflow [https://stackoverflow.com/questions/tagged/sql](url).
