### ISSUE TITLE
No write actions possible from try-catch block

### ISSUE THREAD

**Issue by maschs** [aminroosta/sqlite_modern_cpp#16]
Opening multiple databases prohibits `INSERT` operations on the db opened last. There are no errors thrown, the INSERT is just never performed.

Is this an intended behaviour? I planned to open the second database for logging purposes.

This is happening on a ubuntu 15.10 machine with `clang++-3.7` as compiler (and `-std=c++14`).

**Comment by maschs** [comment]
Ok, I found what's the problem. If you try to do anything write related in a `catch` block it will silently fail.

```cpp
#include <iostream>
#include <string>
#include <sqlite_modern_cpp.h>

using namespace sqlite;
using std::string;

class DBInterface {
    database db;
    database dblog;

public:
    DBInterface( void ) :
        db( database("dbfile.db") ),
        dblog( database("log.db") ) 
    {
    }

    void LogRequest( const string& username, const string& ip, const string& request ) 
    {
        try {
            auto timestamp = std::to_string( time( nullptr ) );

            dblog   <<
                    "create table if not exists log_request ("
                    "   _id integer primary key autoincrement not null,"
                    "   username text,"
                    "   timestamp text,"
                    "   ip text,"
                    "   request text"
                    ");";
            dblog   << "INSERT INTO log_request (username, timestamp, ip, request) VALUES (?,?,?,?);" 
                    << username
                    << timestamp
                    << ip
                    << request;
        } catch ( const std::exception& e ) {
            std::cerr << e.what() << std::endl;
        }
    }
};

int main( void ) 
{
    // --------------------------------------------------------------------------
    // This will not work. If the file is not existing it will create a 0byte file and print
    // an error regarding the missing column log_request.
    // 
    // If the file has been created and the column is existing no error is thrown. But no
    // data is written either.
    // --------------------------------------------------------------------------
    try {
        throw "hello";
    }
    catch ( ... ) {
        try {
            DBInterface interf;
            for ( size_t i = 0; i < 10; ++i ) {
                interf.LogRequest( "test", "127.0.0.1", "hello world" );
            }
        }
        catch ( const std::exception& e ) {
            std::cerr << e.what() << std::endl;
            exit( EXIT_FAILURE );
        }
    }

    // --------------------------------------------------------------------------
    // -- This will not work either.
    // --------------------------------------------------------------------------
    try {
        throw "hello";
    }
    catch ( ... ) {
        DBInterface interf;
        for ( size_t i = 0; i < 10; ++i ) {
            interf.LogRequest( "test", "127.0.0.1", "hello world" );
        }
        exit( EXIT_FAILURE );
    }

    // --------------------------------------------------------------------------
    // This will work perfectly.
    // --------------------------------------------------------------------------
    try {
        DBInterface interf;
        for ( size_t i = 0; i < 10; ++i ) {
            interf.LogRequest( "test", "127.0.0.1", "hello world" );
        }
    }
    catch ( const std::exception& e ) {
        std::cerr << e.what() << std::endl;
        exit( EXIT_FAILURE );
    }
}
```

I will rename the issue.

**Comment by Killili** [comment]
Maybe you are missing a "flush" or something? And SQLITE does not get to write to disk in time for the Process to exit?

There are a lot of strange config options regarding caching and SQLite some of them are set at compile time.

**Comment by maschs** [comment]
How do I manually flush? And why does the last example work perfectly every time? I use the precompiled version of libsqlite3-dev in the ubuntu repositories, I don't really know which flags they use to compile.

**Comment by Killili** [comment]
the last one does proper stack unwinding at application exit i guess. While the other two examples drop out of an exception by calling exit.

**Comment by maschs** [comment]
The same happens without the exit calls, I added them because I thought it was good style.

**Comment by Killili** [comment]
see update

**Comment by edrosten** [comment]
I haven't had time to look properly yet, but I think I know the problem.

I've used std::current_exception to detect unwinding and I should have used std::uncaught_exception. The latter disappears within a catch block, the former does not.

maschs: I'm a bit busy today, but could I ask for a huge favour? If you can modify the example code you gave so that it exits with EXIT_FAILURE if the code behaves unexpectedly (it does currently), and EXIT_SUCCESS otherwise, then I can add it to the nascent unit test suite.

**Comment by Killili** [comment]
Shouldn't the constructor be

```cpp
DBInterface( void ) :
        db( "dbfile.db" ),
        dblog( "log.db" ) 
    {}
```

instead of using the copy constructor?

And you can have multiple DB files on one interface by using the "ATTACH" SQLite feature no need for two.

**Comment by aminroosta** [comment]
@edrosten i was thinking about the same think, can you send a patch ;)

**Comment by edrosten** [comment]
Just to follow up:

to make a unit test, the program must return 0 for success and non zero (below 128, i.e. use 1) for failure. You can print as much stuff to stdout as you like and it will be logged, but won't appear in the summary. Anything printed to stderr will be discarded.

Then drop the .cc file in the tests/ directory.

"make test" will then pick it up automatically. There's currently no way of writing unit test exes depending on multiple cc files.

**Comment by maschs** [comment]
@Killili 
Enclosing it within a seperate scope does not change anything. I updated the constructor, thanks for the hint.

@edrosten 
Sure, I will take a look at it after lunch. My idea would be to just SELECT query the entry we should have written and if it is missing exit( EXIT_FAILURE ).

**Comment by edrosten** [comment]
Thanks!

If you do the test, I'll try the change to uncaught_exception and see if that fixes it.

**Comment by edrosten** [comment]
I've merged some of the pull request. The unit test now passes.
