### ISSUE TITLE
Can't Debug Under GDB

### ISSUE THREAD

**Issue by RenathoAzevedo** [aminroosta/sqlite_modern_cpp#24]
Guys, I decided to use sqlite_modern_cpp libarary in my project, but i came across with one problem, i can't debug with GDB, i'm using NetBeans on cross compilation with a beaglebone black. The compilation process and execution works fine, but when  i try to debug with gdb, it returns a SIGSEV or a SIGILL, that only happens with the sqlite_modern_cpp library, any idea ?

**Comment by kirbyfan64** [comment]
Are you building in debug mode?

**Comment by RenathoAzevedo** [comment]
Sure, the strange is that thedebbuger run fine when the project is without the library, but when I include the library to my project ,i got problems to debug. I tried to debug a simple test with the library included, like this:
 sqlite::database data("/root/test.db");
The debugger runs, but it returns a SIGILL.

**Comment by kirbyfan64** [comment]
Do you mean SIGKILL?

**Comment by kirbyfan64** [comment]
That sounds like your IDE is killing it for some reason.

**Comment by RenathoAzevedo** [comment]
Nope, SIGILL.  For some reason the debugger is giving me those signals. 
Yes, but the IDE is killing only in DEBUG mode, When  i execute the project it runs fine and do what is proposed to.

**Comment by edrosten** [comment]
If you create the executable, can you run it in the debugger from the
command line successfully?

**Comment by RenathoAzevedo** [comment]
Nope, I tried it, but it still gives me those signals, that's strange. 
Here is the output of GDB via command line:
Reading symbols from test.exe...Segmentation fault.

Although GDB gives me a SIGSEV, the test.exe runs normally.
It drives me nuts.

**Comment by unphased** [comment]
what if you compile on the beaglebone? i compile all my raspberry pi software on-device

**Comment by Killili** [comment]
I had it running on my BBB, compiled on there, so no CC. And it runs. While using a CC for another Project i had problems like that. They came from having a wrong libc version in my CC setup. And only using certain parts of the libc would cause a segfault or other strange errors.

Check what libc you are compiling against and what version is on the BB. Or try compiling your project on the BB or even just a test program to check.

**Comment by kirbyfan64** [comment]
That just sounds like a gdb bug. I've encountered those before. What if you try a newer version?

**Comment by kirbyfan64** [comment]
Also see http://stackoverflow.com/questions/24024143/gdb-seg-faults-when-reading-symbols.

**Comment by RenathoAzevedo** [comment]
Hello guys, Sorry, I was travelling.
So, I made it work, but  there's something strange. I don't know why, but, when i took out from the library everything related to utf16 the GDB worked perfectly, without errors or reporting signals. I don't know why, maybe one of you guys can help me to understand it.

**Comment by kirbyfan64** [comment]
When you say utf16, are you using another library?

**Comment by RenathoAzevedo** [comment]
no, I mean everything in sqlite modern library related to 16-bit encoding. I took out: std::u16string, sqlite3_prepare16_v2 and all related to 16-bit encoding. I replaced those lines for their similar 8bit encoding; GDB was returning a SIGILL,SIGSEGV or a message " cannot access memory at address", always in those lines.

**Comment by Killili** [comment]
You should realy check the libc versions in youre CC and runtime environment. As i said using parts of it that are newer on one of the environments can lead to stuff like that.
But as you solved it i will close this now.
