### ISSUE TITLE
Compile Error when using boost::optional.

### ISSUE THREAD

**Issue by UsYer** [aminroosta/sqlite_modern_cpp#25]
Hi,

I ran into a compile error when using the boost::optional extension with VS2015:

    Error	C2248	'sqlite::database_binder::_stmt': cannot access private member declared in class     'sqlite::database_binder'	
    ...\sqlite_modern_cpp\hdr\sqlite_modern_cpp\extensions\boost_optional.h:18	

My code looks like this:

    db << "SELECT `Id`, `ItemTypeId`,`ToUser`,`FromUser`,`Content` FROM `UndeliveredItems`  WHERE ToUser = ?;"
			<< to_user_id 
			>> tie(item.id, item.item_type_id, item.to_user_id, item.from_user_id, item.content);
	
with item.content beeing `boost::optional<std::string> content;`	

It seems like the friend declaration `template<typename T> friend void get_col_from_db(database_binder& ddb, int inx, T& val);` in `class database_binder` is not correctly kicking in.

Do you have any suggestions to fix the issue?

Thank you

**Comment by Killili** [comment]
I'm sorry but recent changes broke the extension system and i did not have the time yet to fix that. The format of the Templates changed so you need to match them again in the header.

**Comment by UsYer** [comment]
Thank you for your quick reply, but I dont seem to be able to follow.
May be you can clarify:

If I look at the signature of the friend declaration in sqlite_modern_cpp.h#L185
```C++
template<typename T> friend void get_col_from_db(database_binder& ddb, int inx, T& val);
```
it seems to already match the signature in boost_optional.h#17
```C++
template <typename BoostOptionalT> void get_col_from_db(database_binder& db, int inx, boost::optional<BoostOptionalT>& o) {
```
Or am I looking at the wrong place?

**Comment by Killili** [comment]
Hi, this time it took a little longer ;)

No the matching template would be 
```c++
template<typename T> friend database_binder&& operator <<(database_binder&& ddb, boost::optional<T> const&& val);
```
And that is where its getting complicated because it drags boost into our common header, and it would have to include it even if you dont want/need it. And i guess thats not wanted.
So having the optional type added by the type expansion system does not work anymore.
I'm trying some work around but had no luck so far. 

Adding that friend template to the database class gets the functions recognized again but then the operator call neasted inside breaks, and i have no idea why or how to fix that. So anyone else got an idea?

**Comment by Killili** [comment]
@aminroosta would it be a good idea to remove the boost reference and go for std::optional even if its experimental? This way we would stay inside std c++ and could add that to the modern_sqlite.h file?

**Comment by aminroosta** [comment]
@Killili i didn't know about `std::optional`, its a really good alternative.
One of the most common use cases for extension system was `boost::optional`,
I think now that we can replace it with standard c++ then that's the way we should go :wink:
We can add a note to the documentation and mention that its experimental.

Great idea killili, thanks again :+1:

**Comment by UsYer** [comment]
Hi,

tanks again for your response @Killili. 
I implemented your suggested workaround by explicitly adding the friend declarations for boost::optional in the database_binder class:
```C++

	template <typename BoostOptionalT> friend database_binder&& operator <<(database_binder&& db, const boost::optional<BoostOptionalT>&& val);
	template <typename BoostOptionalT> friend void get_col_from_db(database_binder& db, int inx, boost::optional<BoostOptionalT>& o);
```
I modified the supplied boost_optional header accordingly and it compiles now: 
```C++

namespace sqlite {
	// boost::optional
	template <typename BoostOptionalT> database_binder&& operator <<(database_binder&& db, const boost::optional<BoostOptionalT>&& val) {
		if(val) {
			return operator << (std::move(db), std::move(*val));
		}
		int hresult;
		if((hresult = sqlite3_bind_null(db._stmt, db._inx)) != SQLITE_OK) {
			db.throw_sqlite_error(hresult);
		}

		++db._inx;
		return std::move(db);
	}
...
}
```
Of course this is far from optimal because of the dependency of boost. For my use case it's not a problem so I'll just use this workaround.

The problem I see with using an experimental c++ feature is, that not all std libs supply it and that it may be removed from the standard in the last minute.

Maybe one could guard the  friend declarations for boost::optional in the database_binder class with an ifdef macro that can be defined by the user. So one would still have a choice to add this dependency.

Kind regards

**Comment by Killili** [comment]
@aminroosta i might be that you did not know because it was rejected from c++14 and might be in c++17 now. So this might be a bit too "modern" for us ;)

I will go the way @UsYer suggested and put it behind #ifdefs and stay with boost but make it a part of the standard header.

**Comment by Killili** [comment]
Should be fixed in master now.

**Comment by UsYer** [comment]
Just wanted to leave a quick reply that the fix works well for me.

Thank you :)
