### ISSUE TITLE
<< std::string not supported

### ISSUE THREAD

**Issue by adnan-emd** [aminroosta/sqlite_modern_cpp#33]
sqldb << my_std_string
Does not compile.  Says "no match for operator<<".

**Comment by aminroosta** [comment]
@adnan-emd You sure ? we have tests in `tests/` folder that already check this case.
can you please add the code snippet that is not working.

**Comment by adnan-emd** [comment]
I’m sure:  simple_examples.cc

string str;
string sql = “SELECT b from FOO where a=?”;
db << sql << 2 >> str;

Won’t compile.

**Comment by Killili** [comment]
Yes thats a case i did not cover in the last update will fix it now, thx.

**Comment by Killili** [comment]
Forgot to fork ... i hope travis is in a good mood today ...
