### ISSUE TITLE
operator << doesn't return a prepared statement

### ISSUE THREAD

**Issue by wibek** [aminroosta/sqlite_modern_cpp#45]
Following the example on the front page:
```c++
database db(":memory:");
auto ps = db << "select a,b from table where something = ? and anotherthing = ?"; // get a prepared parsed and ready statment

// first if needed bind values to it
ps << 5;
int tmp = 8;
ps << tmp;
ps.execute();
```

I get a database_binder which has no execute method.

I expect a prepared statement.

**Comment by aminroosta** [comment]
@wibek Readme is fixed now. `ps` is a `unique_ptr` so users should use `ps->execute()` to access its member functions. thank you :)
