### ISSUE TITLE
Support for unsigned integers

### ISSUE THREAD

**Issue by bjoernpollex** [aminroosta/sqlite_modern_cpp#49]
There is currently no overload of `operator<<` that support `sqlite_uint64`, only `sqlite_int64` (see SQLite documentation on [64-Bit Integer Types][1]). As a side note, the documentation also recommends using the `sqlite3_*` versions over the `sqlite_*` ones.

[1]: https://www.sqlite.org/c3ref/int64.html

**Comment by Killili** [comment]
Hi, see Issue #38 for this.

**Comment by bjoernpollex** [comment]
Ah, interesting, I wasn't aware. That of course makes this issue invalid, I'll close.
