### ISSUE TITLE
Cannot catch constraint exception

### ISSUE THREAD

**Issue by pakerwreah** [aminroosta/sqlite_modern_cpp#53]
I'm trying to insert a row that produces a primary key constraint failure but the program crashes before I can catch the exception.

try {
        db << "INSERT INTO tb_mytable (mytable_id,description) VALUES (?,?)" << 1 << "cannot catch exception";
// inserting again to produce error
        db << "INSERT INTO tb_mytable (mytable_id,description) VALUES (?,?)" << 1 << "cannot catch exception";
    } catch (exception e)
    {
        cerr << e.what() << endl;
    } catch (...)
    {
        cerr << "this does not work either" << endl;
    }

libc++abi.dylib: terminating with uncaught exception of type sqlite::exceptions::constraint: constraint failed
The program has unexpectedly finished.

**Comment by Killili** [comment]
I can confirm that in VS2015. But i cant figure out why....

As soon as the exception is thrown Abort() is getting called as if there where no catch.

**Comment by aminroosta** [comment]
@Killili it seems that we are violating library standards! take a look at [my SO question](http://stackoverflow.com/questions/37788282/why-exceptions-from-unique-ptr-destructor-terminates-the-program)

**Comment by aminroosta** [comment]
But it seems to me that if we don't use `unique_ptr` for `chain_type` then it will no longer be a problem. 
`typedef std::unique_ptr<sqlite::database_binder> chain_type; `

I've spent a couple of hours on this, kind of brain dead now 💀

**Comment by Killili** [comment]
Its strange and i can not understand why the standard enforces the `no throw` rule on `unique_ptr` even if its allowed/not prohibited in the rest of the standard.
The unique_ptr there is a shortcut to make the prepared statements noncopyable so its not really necessary if we make the database_binder class noncopyable. Other then that i cant think of a reason to not change the chain_type.

**Comment by aminroosta** [comment]
@Killili please take a look at #54 and if its ok then merge.
I will create a new release tag, because we have minor breaking changes `ppst->reset() becomes ppst.reset()`.
