### ISSUE TITLE
Archlinux integration !

### ISSUE THREAD

**Issue by funilrys** [aminroosta/sqlite_modern_cpp#58]
Hello,
Just for information I maintain the package of SQL Modern CPP in AUR !
You can find it [here](https://aur.archlinux.org/packages/sqlite_modern_cpp/) or for arch user `yaourt -S sqlite_modern_cpp`

Hava nice day !

**Comment by aminroosta** [comment]
Cool :wink:

I've added a package managers section to the readme.
I'm optimistic that other users will probably create packages for other package managers like nuget or conan as well.

@funilrys Thanks for your contribution 👍

**Comment by aminroosta** [comment]
@funilrys We have new major release :-)

**Comment by funilrys** [comment]
@aminroosta I'm working on the update :)

**Comment by zauguin** [comment]
@funilrys Please take a look at #90, the current release might be broken on some systems.

**Comment by funilrys** [comment]
@zauguin that's why I test all on local before pushing to the world ;)

**Comment by funilrys** [comment]
@aminroosta @zauguin AUR version updated to v3.1

**Comment by zauguin** [comment]
Awesome!

**Comment by aminroosta** [comment]
@funilrys We have new release [v3.2](https://github.com/aminroosta/sqlite_modern_cpp/releases/tag/v3.2), a feature-full and polished release ;-)

**Comment by funilrys** [comment]
@aminroosta Thanks I'm working on it :smiley_cat:

**Comment by funilrys** [comment]
@aminroosta AUR version updated to v3.2
