### ISSUE TITLE
Bad custom constructor behavior in #63 fix

### ISSUE THREAD

**Issue by polesapart** [aminroosta/sqlite_modern_cpp#66]
The fix for #63 as in pull-request #64 have problems.

The custom constructor takes some members from the target object but nullifies them afterwards:

    database_binder(database_binder&& other) :
			_db(std::move(other._db)),
			_sql(std::move(other._sql)),
			_stmt(std::move(other._stmt)),
			_inx(other._inx), execution_started(other.execution_started) {
				_db = nullptr;
				_stmt = nullptr;
		}
    

In the initialization list it takes (moves) the db & stmt, but discards them on the body. The fix is to leave the body empty (I think the idea was to do other.{_db,_stmt} = nullptr instead, but that's not need as the move constructor from std::shared_ptr() will take care of that).

**Comment by aminroosta** [comment]
@polesapart You are absolutely right, my foolish mistake.
https://github.com/aminroosta/sqlite_modern_cpp/commit/13b5c9e1310f2e980676594b1c9386968a7248cd
