### ISSUE TITLE
License file missing?

### ISSUE THREAD

**Issue by VISWESWARAN1998** [aminroosta/sqlite_modern_cpp#67]
Hi, nice library Thanks for sharing but the license file is missing can you please add it Thanks

**Comment by aminroosta** [comment]
@VISWESWARAN1998 The license is MIT, send me a PR with the license file!

**Comment by VISWESWARAN1998** [comment]
Hi,what do you mean by PR? could you explain me briefly?

**Comment by aminroosta** [comment]
@VISWESWARAN1998 PR == Pull Request.
Open a Pull Request which includes the MIT license file.

**Comment by VISWESWARAN1998** [comment]
I think I have created the pull requests

Thanks and Regards,
VISWESWARAN
