### ISSUE TITLE
global database

### ISSUE THREAD

**Issue by mtissington** [aminroosta/sqlite_modern_cpp#68]
I must be missing something here but how do I use the database object as a member variable in a class and then open the database object with a given filename?

**Comment by aminroosta** [comment]
@mtissington `sqlite::database` doesn't have a default constructor. Use a raw pointer or `std::uniqe_ptr<sqlite::database>` in your class.

**Comment by aminroosta** [comment]
@mtissington I'm closing this issue, reopen if you need more info.
