### ISSUE TITLE
open as readonly

### ISSUE THREAD

**Issue by alext234** [aminroosta/sqlite_modern_cpp#71]
I am interested to use 1 sqlite database file shared between 2 programs, 1 as a writer and 1 as a reader. Sometimes I have the exception `locked` or `busy` thrown at the writer program.  
Do you plan to support with flags as those from `open_v2` here?
https://www.sqlite.org/c3ref/open.html

**Comment by aminroosta** [comment]
@alext234 please try #72, i think this should enable you to pass the parameters you want.

I'm not planning on merging this to master yet, not without a unit-test and some documentation.
If you are interested please post a sample code of which parameters you used for `flags` option.
Enough to give me an idea on how to write a unit test :-)

**Comment by mtissington** [comment]
I too would like to see the ability to pass the flags in and open the database as read only.

**Comment by aminroosta** [comment]
I think we need a uniform design for this & #77

**Comment by zauguin** [comment]
@aminroosta I tried to implement such a unified design with #77 in #93.
Tests and documentation are still missing.
