### ISSUE TITLE
GCC 5.4.0 Compilation Error

### ISSUE THREAD

**Issue by comcomservices** [aminroosta/sqlite_modern_cpp#74]
/usr/local/include/sqlite_modern_cpp.h:63: error: 'printf' is not a member of 'sqlite::exceptions'
    if(error_code == SQLITE_ERROR) throw exceptions::error(sqlite3_errstr(error_code));

Any Ideas?

Using GCC 5.4.0 in C++/14 mode, also tested CLANG and get a very similar error.
                                         ^

**Comment by aminroosta** [comment]
@comcomservices I was unable to install gcc54 via homebrew. 
Are you on OSX? If you are, can you guide me on how to install this version of gcc :-)

**Comment by comcomservices** [comment]
I was able to build successfully by changing the line 63 above to throw a generic exception.

My understanding of the project isn't good enough to merge the changes but it should be looked into at some point.

@aminroosta
I'm not on OSX

**Comment by zauguin** [comment]
In your ''bseries" project you [define](https://github.com/comcomservices/bseries/blob/master/debug.h#L8)

```
#define error(...) printf(__VA_ARGS__)
``` 

This causes the problem if you include sqlite_modern_cpp after it.
You can avoid problems like this by using all caps macro names or including your own headers after third party headers.

**Comment by comcomservices** [comment]
@Zauguin wow! Thank you so much! Serisouly i have no idea how you put that all together but makes total sense now.  Seriously, I'm totally mind blown!    You are a freaking genius!
