### ISSUE TITLE
UTF-16 vs UTF-8 encodings

### ISSUE THREAD

**Issue by polesapart** [aminroosta/sqlite_modern_cpp#82]
While convenient for windows users, UTF-16 is, generally speaking, less convenient from a portability point of view. On Linux UTF-8 is more common. Not sure about MacOS.

Currently, sqlite_modern_cpp prefers to use UTF-16 everywhere, from filenames to database encoding and stored strings themselves, and tries to convert from "standard" encoding to u16string using it's iterator construtor.

There are a few shortcomings from these decisions, some of which are manageable and some I consider to be bugs. Let's see:

1. From sqlite wording, regarding database creation: "The default encoding will be UTF-8 for databases created using sqlite3_open() or sqlite3_open_v2(). The default encoding for databases created using sqlite3_open16() will be UTF-16 in the native byte order." And from pragma encoding docs: "Once an encoding has been set for a database, it cannot be changed". The main concern here is that even windows users might prefer the database to store data in utf-8 as most strings are single-byte representable and storing them in UTF-16 takes more disk space. The ideal scenario would be for the user to select the database encoding at database creation time. I do believe (didn't test) that there's still time for user to run db << "PRAGMA encoding = \"UTF-8\""; right after opening the database for the first time, as sqlite uses deferred creation - but this should be documented anyway.

2. In several instances, from accepting the database name in constructor to sending strings to sqlite api, there's a std::string -> std::u16string conversion using u16string's constructor that accepts a char-by-char  iterator, as in std::u16string(orig.begin(), orig.end()). The problem is that std::string charset is undefined, and unsafe for anything other than ASC-II, so while std::string could be e.g. utf8 (as in Linux, depending on user locale), it maybe anything on windows, from CP_ACP to CP_OEMCP), and storing one and retrieving other may lead to hard to track problems.
I'm not sure which would be best here: to have explicit std::u8string overloads which pass utf8 direct to sqlite (which happily expects utf-8), or fix the conversions to utf16 (I don't think using std::u8string and iterators is enough for converting, from what I've read, something like std::wstring_convert or std::codecvt_utf8 might be required). I'm also not sure what to assume with standard std::string .

While the code simply works for most scenarios, specially when the language is english and no special chars are involved, these are serious concerns for i18n-aware applications. Also, my programs all uses utf-8 with multibyte chars and it seems to work - but I didn't conduce enough tests to see if sqlite is handling the queries correctly, i.e. if it's matching the text as it should). Perhaps I'm wrong and std::u16string(u8str.begin(), u8str.end()) actually converts the encoding - but I didn't find any docs suggesting so.

Sorry to put so many points in a single report, but I think these can be further distilled on the discussion.

**Comment by zauguin** [comment]
I'm currently working on this.
There are two primary problems:

1. There is no `std::u8string`, so we can't provide overloads for it. We have to assume that every std::string is UTF-8. But the `std::string` encoding is not even guaranteed to be ASCII compatible...
2. This violates backward compatibility. Right now non ASCII filenames and database contents are wrong, but in a consistent way. If you store some data using `std::string` and get it back with `std::string`, it's the same. Fixing the encoding will break all existing data.

**Comment by zauguin** [comment]
Actually we only use the wrong conversion for filenames and SQL statements, bound parameters are passed correctly. So compatibility problems should only arise from non-ASCII database names.

**Comment by polesapart** [comment]
1. Correct, I have u8string as a bad typedef on some library. I'll have to stop using it :cry: 
2. It's unusual for filenames to have non-ascii chars - unless the program allows the user to pass the database filename, which at least my programs don't. I think a big-fat-warning on readme is enough on this case.

**Comment by mtissington** [comment]
The entire library from icu for handling unicode is based on UTF16 and it's cross platform. While there are some elements that might not need utf16 I think it should remain the default.

**Comment by zauguin** [comment]
@mtissington There are [quite a lot of reasons](http://utf8everywhere.org/) to avoid UTF-16, so we shouldn't force it on people. Especially since UTF-16 isn't normally used except for Windows and some frameworks.
Anyway we don't stop anyone from using it, UTF-8 and UTF-16 will be supported side by side. The default encoding for the database will depend on the encoding you used when you opened the database for the first time. This should be the right choice for almost everyone.

**Comment by polesapart** [comment]
@mtissington With the proposed changes, the *on disk* strings are saved as utf8. That can be reverted with a pragma at database creation. The sqlite api and usage remains the same, it'll be converted to/from utf8 on-the-fly if you use 16 bits. And unless your main use is some asian text with heavy extended character usage (if it fits in 2-bytes in utf16 - there are symbols where two 16-bit values are used to represent a single character), it's likely that on-disk utf8 will be smaller. On my case (Portuguese language, where extended characters such as çãá fits in 1 byte), a 132000 rows text database in utf8 is 50% smaller when compared to utf16. And although converting between encodings have cpu overhead, it's possible that you have a gain nevertheless, specially when using sqlcipher, because disk/io and encryption are the bottlenecks and they'll both reduce as there's less data to process. Of course, benchmarking is required and YMMV.

**Comment by mtissington** [comment]
Let me get this right, I heavily depend on the icu library which is uft16. My database is utf16. But using this api first it's converted to utf8 and sqlite converts it back to utf16 before writing it to disk? I hope I'm mistaken.

**Comment by aminroosta** [comment]
@mtissington Good question, I don't know the answer for sure.

> default encoding for the database will depend on the encoding you used when you opened the database for the first time. 

@zauguin 
My understanding is that if i use `database(std::string const & db_name)`, i will get `utf8` encoding, but if i use `database(std::u16string const & db_name)` i will get `utf16`.

Is that right?

**Comment by aminroosta** [comment]
@mtissington No it's not.

```c++
inline database_binder& operator <<(database_binder& db, const std::string& txt) {
		int hresult;
		if((hresult = sqlite3_bind_text(db._stmt.get(), db._inx, txt.data(), -1, SQLITE_TRANSIENT)) != SQLITE_OK) {
			exceptions::throw_sqlite_error(hresult);
		}

		++db._inx;
		return db;
}

nline database_binder& operator <<(database_binder& db, const std::u16string& txt) {
		int hresult;
		if((hresult = sqlite3_bind_text16(db._stmt.get(), db._inx, txt.data(), -1, SQLITE_TRANSIENT)) != SQLITE_OK) {
			exceptions::throw_sqlite_error(hresult);
		}

		++db._inx;
		return db;
}
```

It depends on if you are passing an `std::string` or `std::u16string`.

**Comment by polesapart** [comment]
In short:

if your database is in utf16 (you can query by PRAGMA encoding):
std::utf16string -> sqlite takes utf16 -> sqlite writes utf16 unchanged.
std::string -> sqlite takes utf8 -> sqlite encodes as utf16 -> writes utf16

If your database is utf8 (will likely happen if the proposed changes are merged as a result of using sqlite_open_v2 instead of sqlite_open_16):
std::utf16string -> sqlite takes utf16 -> sqlite converts from utf16 to utf8 -> writes utf8.
std::string -> sqlite assumes and takes utf8 -> sqlite writes utf8 unchanged.

Reading is the reverse process. So you're not expected to *see* side effects from any implied conversions. It changes nothing in your program - other than eventual performance gains or losses - which are very difficult to estimate because of the cpu <-> I/O tradeoff.

**Comment by mtissington** [comment]
Hmm, For existing database this is good. However when I create a new database I need an option as to what I want to use utf8 or utf16.

**Comment by zauguin** [comment]
@aminroosta That's right.
If you open your database the first time with a std::u16string, you get UTF-16 on-disk, if you use a std::string, you get UTF-8.
@mtissington If you create a new database and you want to pass the name as a std::string, but you still need UTF-16 on-disk encoding for your data, you can use `PRAGMA encoding="UTF-8";` as the _first_ request to the new database. If it's not the first request, it's ignored.
We may add a flag for this later.
