### ISSUE TITLE
variadic function args to database?

### ISSUE THREAD

**Issue by mtissington** [aminroosta/sqlite_modern_cpp#87]
This is not an issue but a request for help please. I have created a variadic function and need to send the variable args list to the database. .... thanks!

    template<typename... AttrTypes>  
    static vector<Action> get(weak_ptr<sqlite::database> awdb_, const T& sql, AttrTypes... args) {
        *awdb_.lock() << sql
	    << args (this is incorrect and needs to be unpacked, how?)
    }

**Comment by zauguin** [comment]
You should look into [fold expressions](http://en.cppreference.com/w/cpp/language/fold).

**Comment by mtissington** [comment]
Thanks - just what I was looking for , but alas I don't think it's in the latest version of Microsoft Visual Studio (2017) :(

**Comment by zauguin** [comment]
These can be emulated by recursively binding the first arguments. For general help with C++ problems I can recommend [stackoverflow](http://stackoverflow.com/)

**Comment by mtissington** [comment]
Got it - I'd like to offer an example to show how to do this - I have the example, how do I push it?

**Comment by zauguin** [comment]
Right now all examples are in the README, but this isn't documenting library functions and the README is quite long already. I think we should create an example folder for this. So you can upload the file for example via the GitHub web interface and then create a pull request.

@aminroosta Is there a policy regarding examples?
