### ISSUE TITLE
latest push breaks build utf16string link

### ISSUE THREAD

**Issue by mtissington** [aminroosta/sqlite_modern_cpp#94]
Using the latest release I now cannot build :( using Visual Studio 2017

error LNK2001: unresolved external symbol "__declspec(dllimport) public: static class std::locale::id std::codecvt<char16_t,char,struct _Mbstatet>::id" (__imp_?id@?$codecvt@_SDU_Mbstatet@@@std@@2V0locale@2@A)

**Comment by zauguin** [comment]
This is a [Visual C++ bug](https://connect.microsoft.com/VisualStudio/feedback/details/1348277/link-error-when-using-std-codecvt-utf8-utf16-char16-t). Microsoft claimed it would be fixed with the next release, but it isn't.
