### ISSUE TITLE
Select calls get called twice

### ISSUE THREAD

**Issue by Killili** [aminroosta/sqlite_modern_cpp#97]
Hi,

while implementing my little Logger feature i noticed that i get to many sqlite_step calls, it looks like the ```_extract``` methods use ```reset()``` at the end and in doing so reset ```execution_started``` which leads to another execution of the query when it leaves the scope. 
I would fix it but i lack the time right now to test it and i think thats an urgent one to fix.

**Comment by zauguin** [comment]
I see four ways to fix this:

We can delete the `reset()` calls from `extract` and `extract_single_value`. Then the user has to reset on his own, which is what the README says anyway. This would be a semi-breaking change.

To avoid breaking existing code, we could keep the reset and manually set `execution_started = true;` again afterward.

On the other hand I do not really know why reset sets `execution_started = false;` in the first place.
I can not think of any reason why somebody would want to explicitly reset a statement and use implicit execution afterward. If we remove this, we have a breaking change too.

We can use `execution_started` or a new flag to track the reset status of the query.
Then reset() as a public interface could be deprecated and the library would be a bit easier to use.

I will try to prepare a pull request for the last approach. What do you think?

**Comment by Killili** [comment]
Part of why i didnt fix it after tracking it down is that i could not explain why that change happend and wanted to take a closer look or have someone that knows why to tell me why ;). 

And without #96 its hard to write a test to check for that in the future so i guess that's a plus point for #96 already.

As i wrote the initial Prepared statement implementation im all for the "breaking" change that restores the behavior outlined in the README, i dont see it a breaking change its a bugfix for undefined behavior.

I do have some time now and would fix it that way if its ok with you.

**Comment by Killili** [comment]
#97 will fix this but Travis broke, anyone got a clue about that?

**Comment by zauguin** [comment]
I have restarted the Travis build, but the main problem is, that [in the prepared statement](https://github.com/aminroosta/sqlite_modern_cpp/blob/master/tests/prepared_statment.cc#L17-L20) test we assume that `_extract*` resets the statement.

**Comment by Killili** [comment]
hm thats bad, i will take a look in a moment.

**Comment by zauguin** [comment]
Fixed by #98
